### ISSUE TITLE
Название блога перед постом

### ISSUE THREAD

**Issue by Spryt** [droptheplot/reader#3]
А-ля: Spryt -> Пост, где "Spryt" - очищенный от доменной зоны и поддомена (blogspot), а так же с заглавной буквы. Сама ссылка может вести либо на главную блога, либо на страницу блога на сервисе (со списком последних постов, а так же статистикой).

**Comment by droptheplot** [comment]
Пока засунул название блога в саму ссылку, а потом лучше сделаем страницу блога на сервисе.
